<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE IMPORT [
  <!ELEMENT IMPORT (ACSPIX, IP, IPDATA, STATISTIC, CHECK)>
  <!ELEMENT ACSPIX     EMPTY>
    <!ATTLIST ACSPIX
      Type     CDATA #REQUIRED
      SN       CDATA #REQUIRED
      Ver      CDATA #REQUIRED
    >
  <!ELEMENT IP    (IPPROFILE*)>
    <!ATTLIST IP
      Name     CDATA #REQUIRED
      SN       CDATA #REQUIRED
      Dt       CDATA #REQUIRED
      Tm       CDATA #REQUIRED
      RestUseDays  CDATA #IMPLIED
      ActiveProf   CDATA #REQUIRED
    >

  <!ELEMENT IPPROFILE (IPTIMESLOT*)>
    <!ATTLIST IPPROFILE
      Name     CDATA #REQUIRED
      Active   CDATA #REQUIRED
      IUday    CDATA #REQUIRED
    >

  <!ELEMENT IPTIMESLOT EMPTY>
    <!ATTLIST IPTIMESLOT
      Number   CDATA #REQUIRED
      IU       CDATA #REQUIRED
    >

  <!ELEMENT IPDATA  ((BASAL|BOLUS|EVENT)*)>

  <!ELEMENT BASAL EMPTY>
   <!ATTLIST BASAL
       Dt        CDATA #REQUIRED
       Tm        CDATA #REQUIRED
       cbrf      CDATA #REQUIRED
       TBRdec    CDATA #IMPLIED
       TBRinc    CDATA #IMPLIED
       profile   CDATA #IMPLIED
       remark    CDATA #IMPLIED
   >

  <!ELEMENT BOLUS EMPTY>
   <!ATTLIST BOLUS
       Dt        CDATA #REQUIRED
       Tm        CDATA #REQUIRED
       type      CDATA #REQUIRED
       cmd       CDATA #IMPLIED
       amount    CDATA #REQUIRED
       remark    CDATA #IMPLIED
   >

  <!ELEMENT EVENT EMPTY>
   <!ATTLIST EVENT
       Dt          CDATA #REQUIRED
       Tm          CDATA #REQUIRED
       shortinfo   CDATA #IMPLIED
       description CDATA #IMPLIED
   >

  <!ELEMENT ST_TIMERANGE (#PCDATA)>
    <!ATTLIST ST_TIMERANGE
      Weeks    CDATA #REQUIRED
      Dt       CDATA #REQUIRED
    >

  <!ELEMENT ST_USETIME_PERCENT (#PCDATA)>
    <!ATTLIST ST_USETIME_PERCENT
      Val      CDATA #REQUIRED
    >
    
  <!ELEMENT ST_BASAL_IU (#PCDATA)>
    <!ATTLIST ST_BASAL_IU
      Val      CDATA #REQUIRED
    >
    
  <!ELEMENT ST_BASAL_PERCENT (#PCDATA)>
    <!ATTLIST ST_BASAL_PERCENT
      Val      CDATA #REQUIRED
    >
    
  <!ELEMENT ST_BOLUSFREQ (#PCDATA)>
    <!ATTLIST ST_BOLUSFREQ
      Val      CDATA #REQUIRED
    >
    
  <!ELEMENT ST_BOLUS_IU (#PCDATA)>
    <!ATTLIST ST_BOLUS_IU
      Val      CDATA #REQUIRED
    >
    
  <!ELEMENT ST_BOLUS_PERCENT (#PCDATA)>
    <!ATTLIST ST_BOLUS_PERCENT
      Val      CDATA #REQUIRED
    >
    
  <!ELEMENT STATISTIC (ST_TIMERANGE, ST_USETIME_PERCENT, ST_BASAL_IU, ST_BASAL_PERCENT, ST_BOLUSFREQ, ST_BOLUS_IU, ST_BOLUS_PERCENT)>

  <!ELEMENT CHECK    EMPTY>
    <!ATTLIST CHECK
      CRC      CDATA #REQUIRED
    >
]>

<IMPORT>
<ACSPIX Type="2106" SN="UI00216344" Ver="3.00.02"/>
<IP Name="Spirit" SN="10026117    " Dt="2010-03-23" Tm="16:54" RestUseDays="1976" ActiveProf="4">
<IPPROFILE Name="1" Active="0" IUday="33.3" >
<IPTIMESLOT Number="1" IU="0.3" />
<IPTIMESLOT Number="2" IU="0.3" />
<IPTIMESLOT Number="3" IU="0.3" />
<IPTIMESLOT Number="4" IU="1.5" />
<IPTIMESLOT Number="5" IU="1.6" />
<IPTIMESLOT Number="6" IU="1.6" />
<IPTIMESLOT Number="7" IU="1.9" />
<IPTIMESLOT Number="8" IU="1.9" />
<IPTIMESLOT Number="9" IU="1.9" />
<IPTIMESLOT Number="10" IU="2.6" />
<IPTIMESLOT Number="11" IU="2.9" />
<IPTIMESLOT Number="12" IU="2.9" />
<IPTIMESLOT Number="13" IU="1.8" />
<IPTIMESLOT Number="14" IU="1.8" />
<IPTIMESLOT Number="15" IU="0.5" />
<IPTIMESLOT Number="16" IU="0.2" />
<IPTIMESLOT Number="17" IU="0.2" />
<IPTIMESLOT Number="18" IU="0.2" />
<IPTIMESLOT Number="19" IU="0.3" />
<IPTIMESLOT Number="20" IU="1.6" />
<IPTIMESLOT Number="21" IU="1.8" />
<IPTIMESLOT Number="22" IU="2.4" />
<IPTIMESLOT Number="23" IU="2.4" />
<IPTIMESLOT Number="24" IU="0.4" />
</IPPROFILE>
<IPPROFILE Name="2" Active="0" IUday="28.0" >
<IPTIMESLOT Number="1" IU="0.1" />
<IPTIMESLOT Number="2" IU="0.1" />
<IPTIMESLOT Number="3" IU="0.1" />
<IPTIMESLOT Number="4" IU="1.6" />
<IPTIMESLOT Number="5" IU="1.5" />
<IPTIMESLOT Number="6" IU="1.5" />
<IPTIMESLOT Number="7" IU="1.5" />
<IPTIMESLOT Number="8" IU="1.7" />
<IPTIMESLOT Number="9" IU="1.9" />
<IPTIMESLOT Number="10" IU="2.0" />
<IPTIMESLOT Number="11" IU="2.0" />
<IPTIMESLOT Number="12" IU="2.0" />
<IPTIMESLOT Number="13" IU="1.8" />
<IPTIMESLOT Number="14" IU="1.6" />
<IPTIMESLOT Number="15" IU="0.3" />
<IPTIMESLOT Number="16" IU="0.2" />
<IPTIMESLOT Number="17" IU="0.1" />
<IPTIMESLOT Number="18" IU="0.1" />
<IPTIMESLOT Number="19" IU="0.2" />
<IPTIMESLOT Number="20" IU="1.7" />
<IPTIMESLOT Number="21" IU="1.8" />
<IPTIMESLOT Number="22" IU="2.1" />
<IPTIMESLOT Number="23" IU="2.0" />
<IPTIMESLOT Number="24" IU="0.1" />
</IPPROFILE>
<IPPROFILE Name="3" Active="0" IUday="30.6" >
<IPTIMESLOT Number="1" IU="0.1" />
<IPTIMESLOT Number="2" IU="0.2" />
<IPTIMESLOT Number="3" IU="0.1" />
<IPTIMESLOT Number="4" IU="1.7" />
<IPTIMESLOT Number="5" IU="1.9" />
<IPTIMESLOT Number="6" IU="1.7" />
<IPTIMESLOT Number="7" IU="2.0" />
<IPTIMESLOT Number="8" IU="2.0" />
<IPTIMESLOT Number="9" IU="2.0" />
<IPTIMESLOT Number="10" IU="2.0" />
<IPTIMESLOT Number="11" IU="1.8" />
<IPTIMESLOT Number="12" IU="1.8" />
<IPTIMESLOT Number="13" IU="1.6" />
<IPTIMESLOT Number="14" IU="1.6" />
<IPTIMESLOT Number="15" IU="0.5" />
<IPTIMESLOT Number="16" IU="0.5" />
<IPTIMESLOT Number="17" IU="0.4" />
<IPTIMESLOT Number="18" IU="0.3" />
<IPTIMESLOT Number="19" IU="0.3" />
<IPTIMESLOT Number="20" IU="1.8" />
<IPTIMESLOT Number="21" IU="1.8" />
<IPTIMESLOT Number="22" IU="2.2" />
<IPTIMESLOT Number="23" IU="2.2" />
<IPTIMESLOT Number="24" IU="0.1" />
</IPPROFILE>
<IPPROFILE Name="4" Active="1" IUday="31.5" >
<IPTIMESLOT Number="1" IU="0.1" />
<IPTIMESLOT Number="2" IU="0.1" />
<IPTIMESLOT Number="3" IU="0.3" />
<IPTIMESLOT Number="4" IU="1.9" />
<IPTIMESLOT Number="5" IU="2.1" />
<IPTIMESLOT Number="6" IU="2.1" />
<IPTIMESLOT Number="7" IU="2.1" />
<IPTIMESLOT Number="8" IU="2.1" />
<IPTIMESLOT Number="9" IU="1.6" />
<IPTIMESLOT Number="10" IU="1.9" />
<IPTIMESLOT Number="11" IU="2.0" />
<IPTIMESLOT Number="12" IU="1.9" />
<IPTIMESLOT Number="13" IU="1.4" />
<IPTIMESLOT Number="14" IU="1.4" />
<IPTIMESLOT Number="15" IU="0.3" />
<IPTIMESLOT Number="16" IU="0.5" />
<IPTIMESLOT Number="17" IU="0.2" />
<IPTIMESLOT Number="18" IU="0.1" />
<IPTIMESLOT Number="19" IU="0.4" />
<IPTIMESLOT Number="20" IU="1.9" />
<IPTIMESLOT Number="21" IU="1.9" />
<IPTIMESLOT Number="22" IU="2.4" />
<IPTIMESLOT Number="23" IU="2.2" />
<IPTIMESLOT Number="24" IU="0.6" />
</IPPROFILE>
<IPPROFILE Name="5" Active="0" IUday="30.3" >
<IPTIMESLOT Number="1" IU="0.1" />
<IPTIMESLOT Number="2" IU="0.1" />
<IPTIMESLOT Number="3" IU="0.1" />
<IPTIMESLOT Number="4" IU="1.7" />
<IPTIMESLOT Number="5" IU="1.7" />
<IPTIMESLOT Number="6" IU="1.7" />
<IPTIMESLOT Number="7" IU="2.0" />
<IPTIMESLOT Number="8" IU="2.0" />
<IPTIMESLOT Number="9" IU="2.0" />
<IPTIMESLOT Number="10" IU="2.0" />
<IPTIMESLOT Number="11" IU="1.8" />
<IPTIMESLOT Number="12" IU="1.8" />
<IPTIMESLOT Number="13" IU="1.6" />
<IPTIMESLOT Number="14" IU="1.6" />
<IPTIMESLOT Number="15" IU="0.5" />
<IPTIMESLOT Number="16" IU="0.5" />
<IPTIMESLOT Number="17" IU="0.4" />
<IPTIMESLOT Number="18" IU="0.3" />
<IPTIMESLOT Number="19" IU="0.3" />
<IPTIMESLOT Number="20" IU="1.8" />
<IPTIMESLOT Number="21" IU="1.8" />
<IPTIMESLOT Number="22" IU="2.2" />
<IPTIMESLOT Number="23" IU="2.2" />
<IPTIMESLOT Number="24" IU="0.1" />
</IPPROFILE>
</IP>
<IPDATA>
<BOLUS Dt="2010-03-23" Tm="" type="" amount="20.90" remark="Bolus Total"/>
<BOLUS Dt="2010-03-23" Tm="" type="" amount="42.88" remark="Bolus+Basal Total"/>
<BASAL Dt="2010-03-23" Tm="16:53" cbrf="0.00" remark="Stop" />
<BASAL Dt="2010-03-23" Tm="16:00" cbrf="0.20" profile="4" />
<BOLUS Dt="2010-03-23" Tm="15:28" type="Scr" amount="1.60" />
<BASAL Dt="2010-03-23" Tm="15:00" cbrf="0.50" profile="4" />
<BASAL Dt="2010-03-23" Tm="14:00" cbrf="0.30" profile="4" />
<BOLUS Dt="2010-03-23" Tm="13:36" type="Scr" amount="10.10" />
<BASAL Dt="2010-03-23" Tm="12:00" cbrf="1.40" profile="4" />
<BASAL Dt="2010-03-23" Tm="11:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-23" Tm="10:00" cbrf="2.00" profile="4" />
<BASAL Dt="2010-03-23" Tm="09:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-23" Tm="08:00" cbrf="1.60" profile="4" />
<EVENT Dt="2010-03-23" Tm="06:35" shortinfo="A4" description="alarm clock" />
<BASAL Dt="2010-03-23" Tm="04:00" cbrf="2.10" profile="4" />
<BASAL Dt="2010-03-23" Tm="03:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-23" Tm="02:00" cbrf="0.30" profile="4" />
<BOLUS Dt="2010-03-23" Tm="01:12" type="Scr" amount="9.20" />
<BASAL Dt="2010-03-23" Tm="00:00" cbrf="0.10" profile="4" />
<BOLUS Dt="2010-03-22" Tm="" type="" amount="35.70" remark="Bolus Total"/>
<BOLUS Dt="2010-03-22" Tm="" type="" amount="66.92" remark="Bolus+Basal Total"/>
<BOLUS Dt="2010-03-22" Tm="23:13" type="Scr" amount="4.50" />
<BASAL Dt="2010-03-22" Tm="23:00" cbrf="0.60" profile="4" />
<BASAL Dt="2010-03-22" Tm="22:00" cbrf="2.20" profile="4" />
<BASAL Dt="2010-03-22" Tm="21:00" cbrf="2.40" profile="4" />
<BOLUS Dt="2010-03-22" Tm="20:20" type="Scr" amount="11.30" />
<BOLUS Dt="2010-03-22" Tm="20:18" type="Scr" amount="0.50" />
<BASAL Dt="2010-03-22" Tm="20:18" cbrf="1.90" profile="4" remark="Run" />
<EVENT Dt="2010-03-22" Tm="20:18" shortinfo="10.40 IU" description="prime infusion set" />
<EVENT Dt="2010-03-22" Tm="20:14" description="cartridge changed" />
<BASAL Dt="2010-03-22" Tm="20:09" cbrf="0.00" remark="Stop" />
<BASAL Dt="2010-03-22" Tm="19:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-22" Tm="18:00" cbrf="0.40" profile="4" />
<BASAL Dt="2010-03-22" Tm="17:00" cbrf="0.10" profile="4" />
<BASAL Dt="2010-03-22" Tm="16:00" cbrf="0.20" profile="4" />
<BOLUS Dt="2010-03-22" Tm="15:48" type="Scr" amount="3.90" />
<BOLUS Dt="2010-03-22" Tm="15:38" type="Scr" amount="6.00" />
<BASAL Dt="2010-03-22" Tm="15:00" cbrf="0.50" profile="4" />
<BASAL Dt="2010-03-22" Tm="14:00" cbrf="0.30" profile="4" />
<EVENT Dt="2010-03-22" Tm="12:15" shortinfo="A1" description="cartridge low" />
<BASAL Dt="2010-03-22" Tm="12:00" cbrf="1.40" profile="4" />
<BOLUS Dt="2010-03-22" Tm="11:12" type="Scr" amount="4.50" />
<BASAL Dt="2010-03-22" Tm="11:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-22" Tm="10:00" cbrf="2.00" profile="4" />
<BASAL Dt="2010-03-22" Tm="09:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-22" Tm="08:00" cbrf="1.60" profile="4" />
<EVENT Dt="2010-03-22" Tm="06:35" shortinfo="A4" description="alarm clock" />
<BASAL Dt="2010-03-22" Tm="04:00" cbrf="2.10" profile="4" />
<BASAL Dt="2010-03-22" Tm="03:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-22" Tm="02:00" cbrf="0.30" profile="4" />
<BOLUS Dt="2010-03-22" Tm="00:45" type="Scr" amount="5.00" />
<BASAL Dt="2010-03-22" Tm="00:00" cbrf="0.10" profile="4" />
<BOLUS Dt="2010-03-21" Tm="" type="" amount="31.90" remark="Bolus Total"/>
<BOLUS Dt="2010-03-21" Tm="" type="" amount="63.40" remark="Bolus+Basal Total"/>
<BASAL Dt="2010-03-21" Tm="23:00" cbrf="0.60" profile="4" />
<BASAL Dt="2010-03-21" Tm="22:00" cbrf="2.20" profile="4" />
<BOLUS Dt="2010-03-21" Tm="21:17" type="Scr" amount="16.00" />
<BASAL Dt="2010-03-21" Tm="21:00" cbrf="2.40" profile="4" />
<BASAL Dt="2010-03-21" Tm="19:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-21" Tm="18:00" cbrf="0.40" profile="4" />
<BASAL Dt="2010-03-21" Tm="17:00" cbrf="0.10" profile="4" />
<BASAL Dt="2010-03-21" Tm="16:00" cbrf="0.20" profile="4" />
<BASAL Dt="2010-03-21" Tm="15:00" cbrf="0.50" profile="4" />
<BASAL Dt="2010-03-21" Tm="14:00" cbrf="0.30" profile="4" />
<BOLUS Dt="2010-03-21" Tm="13:15" type="Scr" amount="2.60" />
<BOLUS Dt="2010-03-21" Tm="12:49" type="Mul" amount="10.10" remark="6.10 / 4.00  1:59 h" />
<BOLUS Dt="2010-03-21" Tm="12:41" type="Scr" amount="3.20" />
<BASAL Dt="2010-03-21" Tm="12:00" cbrf="1.40" profile="4" />
<BASAL Dt="2010-03-21" Tm="11:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-21" Tm="10:00" cbrf="2.00" profile="4" />
<BASAL Dt="2010-03-21" Tm="09:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-21" Tm="08:00" cbrf="1.60" profile="4" />
<EVENT Dt="2010-03-21" Tm="06:35" shortinfo="A4" description="alarm clock" />
<BASAL Dt="2010-03-21" Tm="04:00" cbrf="2.10" profile="4" />
<BASAL Dt="2010-03-21" Tm="03:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-21" Tm="02:00" cbrf="0.30" profile="4" />
<BASAL Dt="2010-03-21" Tm="00:00" cbrf="0.10" profile="4" />
<BOLUS Dt="2010-03-20" Tm="" type="" amount="46.40" remark="Bolus Total"/>
<BOLUS Dt="2010-03-20" Tm="" type="" amount="77.90" remark="Bolus+Basal Total"/>
<BOLUS Dt="2010-03-20" Tm="23:40" type="Scr" amount="6.50" />
<BASAL Dt="2010-03-20" Tm="23:00" cbrf="0.60" profile="4" />
<BASAL Dt="2010-03-20" Tm="22:00" cbrf="2.20" profile="4" />
<BOLUS Dt="2010-03-20" Tm="21:14" type="Scr" amount="1.50" />
<BASAL Dt="2010-03-20" Tm="21:00" cbrf="2.40" profile="4" />
<BOLUS Dt="2010-03-20" Tm="19:34" type="Mul" amount="17.40" remark="10.00 / 7.40  1:59 h" />
<BASAL Dt="2010-03-20" Tm="19:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-20" Tm="18:00" cbrf="0.40" profile="4" />
<BASAL Dt="2010-03-20" Tm="17:00" cbrf="0.10" profile="4" />
<BOLUS Dt="2010-03-20" Tm="16:48" type="Scr" amount="1.60" />
<BASAL Dt="2010-03-20" Tm="16:00" cbrf="0.20" profile="4" />
<BASAL Dt="2010-03-20" Tm="15:00" cbrf="0.50" profile="4" />
<BASAL Dt="2010-03-20" Tm="14:00" cbrf="0.30" profile="4" />
<BOLUS Dt="2010-03-20" Tm="13:07" type="Scr" amount="9.10" />
<BOLUS Dt="2010-03-20" Tm="12:53" type="Scr" amount="2.60" />
<BASAL Dt="2010-03-20" Tm="12:00" cbrf="1.40" profile="4" />
<BASAL Dt="2010-03-20" Tm="11:00" cbrf="1.90" profile="4" />
<BOLUS Dt="2010-03-20" Tm="10:44" type="Scr" amount="3.80" />
<BASAL Dt="2010-03-20" Tm="10:00" cbrf="2.00" profile="4" />
<BASAL Dt="2010-03-20" Tm="09:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-20" Tm="08:00" cbrf="1.60" profile="4" />
<EVENT Dt="2010-03-20" Tm="06:35" shortinfo="A4" description="alarm clock" />
<BASAL Dt="2010-03-20" Tm="04:00" cbrf="2.10" profile="4" />
<BASAL Dt="2010-03-20" Tm="03:00" cbrf="1.90" profile="4" />
<BOLUS Dt="2010-03-20" Tm="02:35" type="Scr" amount="2.00" />
<BASAL Dt="2010-03-20" Tm="02:00" cbrf="0.30" profile="4" />
<BOLUS Dt="2010-03-20" Tm="01:28" type="Scr" amount="1.90" />
<BASAL Dt="2010-03-20" Tm="00:00" cbrf="0.10" profile="4" />
<BOLUS Dt="2010-03-19" Tm="" type="" amount="56.90" remark="Bolus Total"/>
<BOLUS Dt="2010-03-19" Tm="" type="" amount="88.39" remark="Bolus+Basal Total"/>
<BOLUS Dt="2010-03-19" Tm="23:23" type="Scr" amount="3.00" />
<BASAL Dt="2010-03-19" Tm="23:00" cbrf="0.60" profile="4" />
<BASAL Dt="2010-03-19" Tm="22:00" cbrf="2.20" profile="4" />
<BOLUS Dt="2010-03-19" Tm="21:18" type="Scr" amount="23.20" />
<BASAL Dt="2010-03-19" Tm="21:00" cbrf="2.40" profile="4" />
<BASAL Dt="2010-03-19" Tm="19:00" cbrf="1.90" profile="4" />
<BOLUS Dt="2010-03-19" Tm="18:37" type="Scr" amount="3.60" />
<BASAL Dt="2010-03-19" Tm="18:00" cbrf="0.40" profile="4" />
<BASAL Dt="2010-03-19" Tm="17:00" cbrf="0.10" profile="4" />
<BASAL Dt="2010-03-19" Tm="16:00" cbrf="0.20" profile="4" />
<BASAL Dt="2010-03-19" Tm="15:00" cbrf="0.50" profile="4" />
<BASAL Dt="2010-03-19" Tm="14:00" cbrf="0.30" profile="4" />
<BOLUS Dt="2010-03-19" Tm="13:21" type="Scr" amount="9.70" />
<BASAL Dt="2010-03-19" Tm="12:00" cbrf="1.40" profile="4" />
<BASAL Dt="2010-03-19" Tm="11:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-19" Tm="10:00" cbrf="2.00" profile="4" />
<BOLUS Dt="2010-03-19" Tm="09:17" type="Scr" amount="10.80" />
<BASAL Dt="2010-03-19" Tm="09:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-19" Tm="08:00" cbrf="1.60" profile="4" />
<EVENT Dt="2010-03-19" Tm="06:35" shortinfo="A4" description="alarm clock" />
<BASAL Dt="2010-03-19" Tm="04:00" cbrf="2.10" profile="4" />
<BASAL Dt="2010-03-19" Tm="03:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-19" Tm="02:00" cbrf="0.30" profile="4" />
<BOLUS Dt="2010-03-19" Tm="00:54" type="Scr" amount="6.10" />
<BOLUS Dt="2010-03-19" Tm="00:51" type="Scr" amount="0.50" />
<BASAL Dt="2010-03-19" Tm="00:51" cbrf="0.10" profile="4" remark="Run" />
<EVENT Dt="2010-03-19" Tm="00:51" shortinfo="13.90 IU" description="prime infusion set" />
<EVENT Dt="2010-03-19" Tm="00:44" description="cartridge changed" />
<BASAL Dt="2010-03-19" Tm="00:44" cbrf="0.00" remark="Stop" />
<BASAL Dt="2010-03-19" Tm="00:00" cbrf="0.10" profile="4" />
<BOLUS Dt="2010-03-18" Tm="" type="" amount="41.30" remark="Bolus Total"/>
<BOLUS Dt="2010-03-18" Tm="" type="" amount="72.80" remark="Bolus+Basal Total"/>
<BASAL Dt="2010-03-18" Tm="23:00" cbrf="0.60" profile="4" />
<BASAL Dt="2010-03-18" Tm="22:00" cbrf="2.20" profile="4" />
<BASAL Dt="2010-03-18" Tm="21:00" cbrf="2.40" profile="4" />
<BOLUS Dt="2010-03-18" Tm="20:26" type="Scr" amount="2.60" />
<BOLUS Dt="2010-03-18" Tm="19:48" type="Scr" amount="15.40" />
<EVENT Dt="2010-03-18" Tm="19:47" shortinfo="A1" description="cartridge low" />
<BASAL Dt="2010-03-18" Tm="19:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-18" Tm="18:00" cbrf="0.40" profile="4" />
<BASAL Dt="2010-03-18" Tm="17:00" cbrf="0.10" profile="4" />
<BASAL Dt="2010-03-18" Tm="16:00" cbrf="0.20" profile="4" />
<BASAL Dt="2010-03-18" Tm="15:00" cbrf="0.50" profile="4" />
<BASAL Dt="2010-03-18" Tm="14:00" cbrf="0.30" profile="4" />
<BOLUS Dt="2010-03-18" Tm="13:07" type="Scr" amount="13.20" />
<BASAL Dt="2010-03-18" Tm="12:00" cbrf="1.40" profile="4" />
<BASAL Dt="2010-03-18" Tm="11:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-18" Tm="10:00" cbrf="2.00" profile="4" />
<BOLUS Dt="2010-03-18" Tm="09:10" type="Scr" amount="10.10" />
<BASAL Dt="2010-03-18" Tm="09:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-18" Tm="08:00" cbrf="1.60" profile="4" />
<EVENT Dt="2010-03-18" Tm="06:35" shortinfo="A4" description="alarm clock" />
<BASAL Dt="2010-03-18" Tm="04:00" cbrf="2.10" profile="4" />
<BASAL Dt="2010-03-18" Tm="03:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-18" Tm="02:00" cbrf="0.30" profile="4" />
<BASAL Dt="2010-03-18" Tm="00:00" cbrf="0.10" profile="4" />
<BOLUS Dt="2010-03-17" Tm="" type="" amount="49.20" remark="Bolus Total"/>
<BOLUS Dt="2010-03-17" Tm="" type="" amount="80.70" remark="Bolus+Basal Total"/>
<BOLUS Dt="2010-03-17" Tm="23:43" type="Scr" amount="3.20" />
<BOLUS Dt="2010-03-17" Tm="23:08" type="Scr" amount="3.90" />
<BASAL Dt="2010-03-17" Tm="23:00" cbrf="0.60" profile="4" />
<BOLUS Dt="2010-03-17" Tm="22:59" type="Scr" amount="2.80" />
<BOLUS Dt="2010-03-17" Tm="22:13" type="Scr" amount="2.20" />
<BASAL Dt="2010-03-17" Tm="22:00" cbrf="2.20" profile="4" />
<BASAL Dt="2010-03-17" Tm="21:00" cbrf="2.40" profile="4" />
<BASAL Dt="2010-03-17" Tm="19:00" cbrf="1.90" profile="4" />
<BOLUS Dt="2010-03-17" Tm="18:15" type="Scr" amount="11.20" />
<BASAL Dt="2010-03-17" Tm="18:00" cbrf="0.40" profile="4" />
<BASAL Dt="2010-03-17" Tm="17:00" cbrf="0.10" profile="4" />
<BASAL Dt="2010-03-17" Tm="16:00" cbrf="0.20" profile="4" />
<BASAL Dt="2010-03-17" Tm="15:00" cbrf="0.50" profile="4" />
<BASAL Dt="2010-03-17" Tm="14:00" cbrf="0.30" profile="4" />
<BOLUS Dt="2010-03-17" Tm="12:56" type="Scr" amount="17.00" />
<BASAL Dt="2010-03-17" Tm="12:00" cbrf="1.40" profile="4" />
<BASAL Dt="2010-03-17" Tm="11:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-17" Tm="10:00" cbrf="2.00" profile="4" />
<BASAL Dt="2010-03-17" Tm="09:00" cbrf="1.90" profile="4" />
<BOLUS Dt="2010-03-17" Tm="08:39" type="Scr" amount="8.90" />
<BASAL Dt="2010-03-17" Tm="08:00" cbrf="1.60" profile="4" />
<EVENT Dt="2010-03-17" Tm="06:35" shortinfo="A4" description="alarm clock" />
<BASAL Dt="2010-03-17" Tm="04:00" cbrf="2.10" profile="4" />
<BASAL Dt="2010-03-17" Tm="03:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-17" Tm="02:00" cbrf="0.30" profile="4" />
<BASAL Dt="2010-03-17" Tm="00:00" cbrf="0.10" profile="4" />
<BOLUS Dt="2010-03-16" Tm="" type="" amount="42.60" remark="Bolus Total"/>
<BOLUS Dt="2010-03-16" Tm="" type="" amount="74.10" remark="Bolus+Basal Total"/>
<BASAL Dt="2010-03-16" Tm="23:00" cbrf="0.60" profile="4" />
<BOLUS Dt="2010-03-16" Tm="22:35" type="Scr" amount="3.90" />
<BASAL Dt="2010-03-16" Tm="22:00" cbrf="2.20" profile="4" />
<BOLUS Dt="2010-03-16" Tm="21:09" type="Scr" amount="8.10" />
<BASAL Dt="2010-03-16" Tm="21:00" cbrf="2.40" profile="4" />
<BASAL Dt="2010-03-16" Tm="19:00" cbrf="1.90" profile="4" />
<BOLUS Dt="2010-03-16" Tm="18:09" type="Scr" amount="7.00" />
<BASAL Dt="2010-03-16" Tm="18:00" cbrf="0.40" profile="4" />
<BOLUS Dt="2010-03-16" Tm="17:54" type="Scr" amount="7.40" />
<BASAL Dt="2010-03-16" Tm="17:00" cbrf="0.10" profile="4" />
<BASAL Dt="2010-03-16" Tm="16:00" cbrf="0.20" profile="4" />
<BASAL Dt="2010-03-16" Tm="15:00" cbrf="0.50" profile="4" />
<BASAL Dt="2010-03-16" Tm="14:00" cbrf="0.30" profile="4" />
<BOLUS Dt="2010-03-16" Tm="13:07" type="Scr" amount="14.70" />
<BASAL Dt="2010-03-16" Tm="12:00" cbrf="1.40" profile="4" />
<BASAL Dt="2010-03-16" Tm="11:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-16" Tm="10:00" cbrf="2.00" profile="4" />
<BOLUS Dt="2010-03-16" Tm="09:01" type="Scr" amount="1.50" />
<BASAL Dt="2010-03-16" Tm="09:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-16" Tm="08:00" cbrf="1.60" profile="4" />
<EVENT Dt="2010-03-16" Tm="06:35" shortinfo="A4" description="alarm clock" />
<BASAL Dt="2010-03-16" Tm="04:00" cbrf="2.10" profile="4" />
<BASAL Dt="2010-03-16" Tm="03:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-16" Tm="02:00" cbrf="0.30" profile="4" />
<BASAL Dt="2010-03-16" Tm="00:00" cbrf="0.10" profile="4" />
<BOLUS Dt="2010-03-15" Tm="" type="" amount="36.10" remark="Bolus Total"/>
<BOLUS Dt="2010-03-15" Tm="" type="" amount="65.99" remark="Bolus+Basal Total"/>
<BASAL Dt="2010-03-15" Tm="23:00" cbrf="0.60" profile="4" />
<BASAL Dt="2010-03-15" Tm="22:00" cbrf="2.20" profile="4" />
<BOLUS Dt="2010-03-15" Tm="21:35" type="Scr" amount="1.90" />
<BASAL Dt="2010-03-15" Tm="21:00" cbrf="2.40" profile="4" />
<BASAL Dt="2010-03-15" Tm="19:00" cbrf="1.90" profile="4" />
<BOLUS Dt="2010-03-15" Tm="18:44" type="Scr" amount="11.00" />
<BASAL Dt="2010-03-15" Tm="18:00" cbrf="0.40" profile="4" />
<BASAL Dt="2010-03-15" Tm="17:00" cbrf="0.10" profile="4" />
<BASAL Dt="2010-03-15" Tm="16:00" cbrf="0.20" profile="4" />
<BASAL Dt="2010-03-15" Tm="15:00" cbrf="0.50" profile="4" />
<BASAL Dt="2010-03-15" Tm="14:00" cbrf="0.30" profile="4" />
<BOLUS Dt="2010-03-15" Tm="12:33" type="Scr" amount="15.60" />
<BASAL Dt="2010-03-15" Tm="12:00" cbrf="1.40" profile="4" />
<BASAL Dt="2010-03-15" Tm="11:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-15" Tm="10:00" cbrf="2.00" profile="4" />
<BASAL Dt="2010-03-15" Tm="09:00" cbrf="1.90" profile="4" />
<BOLUS Dt="2010-03-15" Tm="08:47" type="Scr" amount="3.00" />
<BOLUS Dt="2010-03-15" Tm="08:20" type="Scr" amount="0.80" />
<BOLUS Dt="2010-03-15" Tm="08:19" type="Scr" amount="0.50" />
<BASAL Dt="2010-03-15" Tm="08:19" cbrf="1.60" profile="4" remark="Run" />
<EVENT Dt="2010-03-15" Tm="08:17" shortinfo="13.70 IU" description="prime infusion set" />
<EVENT Dt="2010-03-15" Tm="08:13" description="cartridge changed" />
<BASAL Dt="2010-03-15" Tm="07:30" cbrf="0.00" remark="Stop" />
<EVENT Dt="2010-03-15" Tm="07:30" shortinfo="E1" description="cartridge empty" />
<EVENT Dt="2010-03-15" Tm="06:35" shortinfo="A4" description="alarm clock" />
<BASAL Dt="2010-03-15" Tm="04:00" cbrf="2.10" profile="4" />
<BASAL Dt="2010-03-15" Tm="03:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-15" Tm="02:00" cbrf="0.30" profile="4" />
<BOLUS Dt="2010-03-15" Tm="01:17" type="Scr" amount="3.30" />
<BASAL Dt="2010-03-15" Tm="00:58" cbrf="0.10" profile="4" remark="Run" />
<BASAL Dt="2010-03-15" Tm="00:29" cbrf="0.00" remark="Stop" />
<BASAL Dt="2010-03-15" Tm="00:00" cbrf="0.10" profile="4" />
<BOLUS Dt="2010-03-14" Tm="" type="" amount="30.60" remark="Bolus Total"/>
<BOLUS Dt="2010-03-14" Tm="" type="" amount="62.10" remark="Bolus+Basal Total"/>
<BASAL Dt="2010-03-14" Tm="23:00" cbrf="0.60" profile="4" />
<BOLUS Dt="2010-03-14" Tm="22:15" type="Scr" amount="2.60" />
<BASAL Dt="2010-03-14" Tm="22:00" cbrf="2.20" profile="4" />
<EVENT Dt="2010-03-14" Tm="21:21" shortinfo="A1" description="cartridge low" />
<BASAL Dt="2010-03-14" Tm="21:00" cbrf="2.40" profile="4" />
<BOLUS Dt="2010-03-14" Tm="20:42" type="Scr" amount="12.40" />
<BASAL Dt="2010-03-14" Tm="19:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-14" Tm="18:00" cbrf="0.40" profile="4" />
<BOLUS Dt="2010-03-14" Tm="17:46" type="Scr" amount="1.60" />
<BASAL Dt="2010-03-14" Tm="17:00" cbrf="0.10" profile="4" />
<BASAL Dt="2010-03-14" Tm="16:00" cbrf="0.20" profile="4" />
<BASAL Dt="2010-03-14" Tm="15:00" cbrf="0.50" profile="4" />
<BASAL Dt="2010-03-14" Tm="14:00" cbrf="0.30" profile="4" />
<BOLUS Dt="2010-03-14" Tm="13:38" type="Scr" amount="7.80" />
<BOLUS Dt="2010-03-14" Tm="13:32" type="Scr" amount="2.10" />
<BASAL Dt="2010-03-14" Tm="12:00" cbrf="1.40" profile="4" />
<BASAL Dt="2010-03-14" Tm="11:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-14" Tm="10:00" cbrf="2.00" profile="4" />
<BASAL Dt="2010-03-14" Tm="09:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-14" Tm="08:00" cbrf="1.60" profile="4" />
<EVENT Dt="2010-03-14" Tm="06:35" shortinfo="A4" description="alarm clock" />
<BASAL Dt="2010-03-14" Tm="04:00" cbrf="2.10" profile="4" />
<BASAL Dt="2010-03-14" Tm="03:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-14" Tm="02:00" cbrf="0.30" profile="4" />
<BOLUS Dt="2010-03-14" Tm="01:57" type="Scr" amount="2.50" />
<BOLUS Dt="2010-03-14" Tm="00:04" type="Scr" amount="1.60" />
<BASAL Dt="2010-03-14" Tm="00:00" cbrf="0.10" profile="4" />
<BOLUS Dt="2010-03-13" Tm="" type="" amount="30.70" remark="Bolus Total"/>
<BOLUS Dt="2010-03-13" Tm="" type="" amount="62.20" remark="Bolus+Basal Total"/>
<BASAL Dt="2010-03-13" Tm="23:00" cbrf="0.60" profile="4" />
<BASAL Dt="2010-03-13" Tm="22:00" cbrf="2.20" profile="4" />
<BOLUS Dt="2010-03-13" Tm="21:23" type="Scr" amount="17.10" />
<BASAL Dt="2010-03-13" Tm="21:00" cbrf="2.40" profile="4" />
<BOLUS Dt="2010-03-13" Tm="19:08" type="Scr" amount="1.60" />
<BASAL Dt="2010-03-13" Tm="19:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-13" Tm="18:00" cbrf="0.40" profile="4" />
<BASAL Dt="2010-03-13" Tm="17:00" cbrf="0.10" profile="4" />
<BASAL Dt="2010-03-13" Tm="16:00" cbrf="0.20" profile="4" />
<BASAL Dt="2010-03-13" Tm="15:00" cbrf="0.50" profile="4" />
<BOLUS Dt="2010-03-13" Tm="14:03" type="Scr" amount="1.30" />
<BASAL Dt="2010-03-13" Tm="14:00" cbrf="0.30" profile="4" />
<BOLUS Dt="2010-03-13" Tm="13:13" type="Scr" amount="9.10" />
<BOLUS Dt="2010-03-13" Tm="13:04" type="Scr" amount="1.60" />
<BASAL Dt="2010-03-13" Tm="12:00" cbrf="1.40" profile="4" />
<BASAL Dt="2010-03-13" Tm="11:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-13" Tm="10:00" cbrf="2.00" profile="4" />
<BASAL Dt="2010-03-13" Tm="09:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-13" Tm="08:00" cbrf="1.60" profile="4" />
<EVENT Dt="2010-03-13" Tm="06:35" shortinfo="A4" description="alarm clock" />
<BASAL Dt="2010-03-13" Tm="04:00" cbrf="2.10" profile="4" />
<BASAL Dt="2010-03-13" Tm="03:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-13" Tm="02:00" cbrf="0.30" profile="4" />
<BASAL Dt="2010-03-13" Tm="00:00" cbrf="0.10" profile="4" />
<BOLUS Dt="2010-03-12" Tm="" type="" amount="47.50" remark="Bolus Total"/>
<BOLUS Dt="2010-03-12" Tm="" type="" amount="79.00" remark="Bolus+Basal Total"/>
<BOLUS Dt="2010-03-12" Tm="23:45" type="Scr" amount="1.90" />
<BOLUS Dt="2010-03-12" Tm="23:40" type="Scr" amount="3.90" />
<BASAL Dt="2010-03-12" Tm="23:00" cbrf="0.60" profile="4" />
<BASAL Dt="2010-03-12" Tm="22:00" cbrf="2.20" profile="4" />
<BOLUS Dt="2010-03-12" Tm="21:47" type="Scr" amount="1.90" />
<BASAL Dt="2010-03-12" Tm="21:00" cbrf="2.40" profile="4" />
<BOLUS Dt="2010-03-12" Tm="20:16" type="Scr" amount="1.80" />
<BASAL Dt="2010-03-12" Tm="19:00" cbrf="1.90" profile="4" />
<BOLUS Dt="2010-03-12" Tm="18:42" type="Scr" amount="9.20" />
<BOLUS Dt="2010-03-12" Tm="18:19" type="Scr" amount="7.30" />
<BASAL Dt="2010-03-12" Tm="18:00" cbrf="0.40" profile="4" />
<BASAL Dt="2010-03-12" Tm="17:00" cbrf="0.10" profile="4" />
<BASAL Dt="2010-03-12" Tm="16:00" cbrf="0.20" profile="4" />
<BASAL Dt="2010-03-12" Tm="15:00" cbrf="0.50" profile="4" />
<BASAL Dt="2010-03-12" Tm="14:00" cbrf="0.30" profile="4" />
<BOLUS Dt="2010-03-12" Tm="12:02" type="Scr" amount="15.40" />
<BASAL Dt="2010-03-12" Tm="12:00" cbrf="1.40" profile="4" />
<BASAL Dt="2010-03-12" Tm="11:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-12" Tm="10:00" cbrf="2.00" profile="4" />
<BASAL Dt="2010-03-12" Tm="09:00" cbrf="1.90" profile="4" />
<BOLUS Dt="2010-03-12" Tm="08:52" type="Scr" amount="6.10" />
<BASAL Dt="2010-03-12" Tm="08:00" cbrf="1.60" profile="4" />
<EVENT Dt="2010-03-12" Tm="06:35" shortinfo="A4" description="alarm clock" />
<BASAL Dt="2010-03-12" Tm="04:00" cbrf="2.10" profile="4" />
<BASAL Dt="2010-03-12" Tm="03:00" cbrf="1.90" profile="4" />
<BASAL Dt="2010-03-12" Tm="02:00" cbrf="0.30" profile="4" />
<BASAL Dt="2010-03-12" Tm="00:00" cbrf="0.10" profile="4" />
<BOLUS Dt="2010-03-11" Tm="" type="" amount="43.60" remark="Bolus Total"/>
<BOLUS Dt="2010-03-11" Tm="" type="" amount="74.91" remark="Bolus+Basal Total"/>
<BOLUS Dt="2010-03-11" Tm="23:14" type="Scr" amount="3.00" />
<BOLUS Dt="2010-03-11" Tm="23:12" type="Scr" amount="3.90" />
<BASAL Dt="2010-03-11" Tm="23:00" cbrf="0.60" profile="4" />
<BOLUS Dt="2010-03-11" Tm="22:38" type="Scr" amount="3.70" />